#!/usr/bin/env node
/* Generated by Fixora VS Code extension.
 * Direct GitHub Action backend gate.
 * This script does not run the scanner locally and does not require @fixora/cli.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');

const IGNORED_PARTS = new Set(['.git', '.fixora', 'node_modules', 'venv', '.venv', '.venv-snyk', '__pycache__', 'dist', 'build', '.next', 'target', 'coverage', '.pytest_cache']);
const CODE_EXTENSIONS = new Set(['.py', '.js', '.jsx', '.ts', '.tsx', '.java', '.go', '.rb', '.php']);
const IAC_EXTENSIONS = new Set(['.tf', '.tfvars']);
const SPECIAL_FILES = new Set(['package.json', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'requirements.txt', 'Pipfile', 'Pipfile.lock', 'poetry.lock', 'pyproject.toml', 'Dockerfile', 'docker-compose.yml', 'docker-compose.yaml']);

function runGit(args) {
  return execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
}

function safeRunGit(args) {
  try { return runGit(args); } catch { return ''; }
}

function repoRoot() {
  return safeRunGit(['rev-parse', '--show-toplevel']) || process.cwd();
}

function normalizeRepoPath(filePath) {
  return String(filePath || '').replace(/\\/g, '/').replace(/^\.\//, '').trim();
}

function hasIgnoredPart(filePath) {
  return normalizeRepoPath(filePath).split('/').some((part) => IGNORED_PARTS.has(part));
}

function isIgnoredGeneratedFile(filePath) {
  const f = normalizeRepoPath(filePath).toLowerCase();
  return (
    f === '.github/scripts/fixora-gate.js' ||
    f === 'fixora-report.json' ||
    f === 'fixora.sarif' ||
    f.includes('.before-fixora-')
  );
}

function isKubernetesOrWorkflowYaml(filePath) {
  const f = normalizeRepoPath(filePath).toLowerCase();
  return (f.endsWith('.yml') || f.endsWith('.yaml')) && (
    f.startsWith('k8s/') || f.startsWith('kubernetes/') || f.startsWith('manifests/') || f.startsWith('.github/workflows/')
  );
}

function isDockerfile(filePath) {
  const base = path.basename(normalizeRepoPath(filePath));
  return base === 'Dockerfile' || base.endsWith('.Dockerfile');
}

function isSupportedFile(filePath) {
  const f = normalizeRepoPath(filePath);
  if (!f || hasIgnoredPart(f) || isIgnoredGeneratedFile(f)) return false;
  const base = path.basename(f);
  const ext = path.extname(f).toLowerCase();
  if (CODE_EXTENSIONS.has(ext)) return true;
  if (IAC_EXTENSIONS.has(ext)) return true;
  if (SPECIAL_FILES.has(base)) return true;
  if (isDockerfile(f)) return true;
  if (isKubernetesOrWorkflowYaml(f)) return true;
  return false;
}

function getAllFiles() {
  let out = safeRunGit(['ls-files']);
  if (!out) out = safeRunGit(['ls-tree', '-r', '--name-only', 'HEAD']);
  return Array.from(new Set(String(out || '').split(/\r?\n/).map(normalizeRepoPath).filter(isSupportedFile))).sort();
}

function readFileUtf8(root, file) {
  return fs.readFileSync(path.join(root, file), 'utf8');
}

function detectLanguage(file) {
  const f = normalizeRepoPath(file);
  const ext = path.extname(f).toLowerCase();
  const base = path.basename(f);
  if (ext === '.py') return 'python';
  if (ext === '.js' || ext === '.jsx') return 'javascript';
  if (ext === '.ts' || ext === '.tsx') return 'typescript';
  if (ext === '.java') return 'java';
  if (ext === '.go') return 'go';
  if (ext === '.rb') return 'ruby';
  if (ext === '.php') return 'php';
  if (ext === '.tf' || ext === '.tfvars') return 'terraform';
  if (base === 'Dockerfile' || base.endsWith('.Dockerfile')) return 'dockerfile';
  if (ext === '.yml' || ext === '.yaml') return 'yaml';
  if (base === 'package.json' || base === 'package-lock.json') return 'json';
  if (base === 'requirements.txt') return 'pip-requirements';
  return 'auto';
}

function contentHash(code) {
  return crypto.createHash('sha256').update(String(code || ''), 'utf8').digest('hex');
}

function httpJson(urlString, body, token, timeoutMs) {
  const url = new URL(urlString);
  const lib = url.protocol === 'https:' ? require('https') : require('http');
  return new Promise((resolve, reject) => {
    const payload = Buffer.from(JSON.stringify(body), 'utf8');
    const req = lib.request({
      protocol: url.protocol,
      hostname: url.hostname,
      port: url.port || (url.protocol === 'https:' ? 443 : 80),
      path: url.pathname + url.search,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + token,
        'Content-Length': String(payload.length),
      },
    }, (res) => {
      let data = '';
      res.setEncoding('utf8');
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        if (res.statusCode < 200 || res.statusCode >= 300) {
          reject(new Error('HTTP ' + res.statusCode + ': ' + data));
          return;
        }
        try { resolve(data ? JSON.parse(data) : {}); }
        catch (err) { reject(new Error('Invalid JSON from Fixora backend: ' + (err && err.message ? err.message : err))); }
      });
    });
    req.setTimeout(timeoutMs, () => req.destroy(new Error('request timeout after ' + timeoutMs + 'ms')));
    req.on('error', reject);
    req.write(payload);
    req.end();
  });
}

function severityValue(value) {
  if (value && typeof value === 'object' && 'value' in value) return String(value.value || '').toUpperCase();
  return String(value || '').toUpperCase();
}

function printGate(gate) {
  const allowed = !!gate.allowed;
  console.error('Fixora GitHub Action Gate: ' + (allowed ? 'ALLOWED' : 'BLOCKED'));
  console.error('Policy: threshold=' + (gate.threshold || process.env.FIXORA_GATE_THRESHOLD || 'HIGH') + ' trusted_only=' + String(gate.trusted_only));
  console.error('Scanned files: ' + (gate.files_scanned || 0) + ', findings: ' + (gate.total_findings || 0) + ', blocked: ' + (gate.blocked_count || 0));
  if (Array.isArray(gate.blocked_findings) && gate.blocked_findings.length) {
    console.error('');
    console.error('Blocked findings:');
    for (const item of gate.blocked_findings) {
      const file = item.file || (item.finding && (item.finding.display_file || item.finding.file)) || '';
      const line = item.line || (item.finding && (item.finding.display_line || item.finding.line)) || 1;
      const sev = severityValue(item.severity || (item.finding && item.finding.severity) || 'UNKNOWN');
      const cwe = item.cwe || (item.finding && item.finding.cwe) || 'CWE-UNKNOWN';
      const title = item.title || (item.finding && (item.finding.title || item.finding.description)) || 'Security finding';
      console.error('- ' + sev + ' ' + cwe + ' ' + file + ':' + line + ' ' + title);
      if (item.reason) console.error('  Why: ' + item.reason);
      if (item.suggestion) console.error('  Fix first: ' + item.suggestion);
    }
  }
  if (Array.isArray(gate.errors) && gate.errors.length) {
    console.error('');
    console.error('Errors:');
    for (const err of gate.errors) console.error('- ' + (err.file || 'unknown') + ': ' + (err.error || JSON.stringify(err)));
  }
}

async function main() {
  const root = repoRoot();
  process.chdir(root);

  const backendUrl = String(process.env.FIXORA_BACKEND_URL || '').replace(/\/+$/, '');

function readLocalFixoraToken() {
  const candidates = [
    path.join(process.cwd(), '.fixora', 'token'),
    path.join(process.env.USERPROFILE || '', '.fixora', 'token'),
    path.join(process.env.HOME || '', '.fixora', 'token'),
  ].filter(Boolean);

  for (const p of candidates) {
    try {
      if (fs.existsSync(p)) {
        const value = fs.readFileSync(p, 'utf8').trim();
        if (value) return value;
      }
    } catch {}
  }
  return '';
}

  const token = String(process.env.FIXORA_TOKEN || process.env.FIXORA_AUTH_TOKEN || readLocalFixoraToken() || '').trim();
  const threshold = String(process.env.FIXORA_GATE_THRESHOLD || 'HIGH').toUpperCase();
  const timeoutMs = Number(process.env.FIXORA_GATE_TIMEOUT_MS || 1800000);

  if (!backendUrl) throw new Error('Missing FIXORA_BACKEND_URL GitHub secret');
  if (!token) throw new Error('Missing FIXORA_TOKEN GitHub secret and no local .fixora/token found');

  const fileNames = getAllFiles();
  if (!fileNames.length) {
    console.error('Fixora: no supported files found.');
    return;
  }

  const files = [];
  for (const file of fileNames) {
    let code = '';
    try { code = readFileUtf8(root, file); } catch { continue; }
    if (!code || !code.trim()) continue;
    files.push({
      filename: file,
      fs_path: path.join(root, file),
      language: detectLanguage(file),
      content_hash: contentHash(code),
      code,
    });
  }

  console.error('Fixora: scanning ' + files.length + ' file(s) with deployed backend gate, mode github-action, supply-chain=auto...');

  const request = {
    project_name: process.env.GITHUB_REPOSITORY || path.basename(root),
    files,
    threshold,
    smart_mode: true,
    trusted_only: true,
    min_confidence: 0.0,
  };

  let gate;
  try {
    const sarifResponse = await httpJson(backendUrl + '/api/v1/devsecops/sarif', request, token, timeoutMs);
    gate = sarifResponse.gate || sarifResponse;
    if (sarifResponse.sarif) fs.writeFileSync(path.join(root, 'fixora.sarif'), JSON.stringify(sarifResponse.sarif, null, 2), 'utf8');
  } catch (err) {
    console.error('Fixora: SARIF endpoint failed, falling back to gate endpoint: ' + (err && err.message ? err.message : err));
    gate = await httpJson(backendUrl + '/api/v1/devsecops/gate', request, token, timeoutMs);
  }

  fs.writeFileSync(path.join(root, 'fixora-report.json'), JSON.stringify(gate, null, 2), 'utf8');
  printGate(gate);
  process.exit(Number(gate.exit_code != null ? gate.exit_code : (gate.allowed ? 0 : 1)));
}

main().catch((err) => {
  console.error('Fixora GitHub Action error: ' + (err && err.message ? err.message : err));
  process.exit(1);
});
